#!/bin/bash

###############################################################################
# Aliases Definition - All shell aliases for InitDev setup
###############################################################################

declare -a ALIASES=(
  "# ----General Aliases----"
  "alias enableNeoCode='sudo chown -R $USER /usr/share/code/'"
  "alias adios='poweroff'"
  "alias spdt='speedtest-cli'"
  "alias le='eza --level=1 --tree --icons'"
  "alias lr='eza --tree --level=1 --all --icons'"

  "# ----Package Manager Aliases----"
  "alias bund='bun dev'"
  "alias bunb='bun run build'"
  "alias bunf='bun run format'"
  "alias bunt='bun run test'"
  "alias bunr='bun run'"
  "alias buns='bun run start'"
  "alias buni='bun i'"
  "alias bunp='bun run preview'"
  "alias pnpmx='pnpm dlx'"
  "alias pnpmd='pnpm run dev'"
  "alias pnpmb='pnpm run build'"
  "alias pnpms='pnpm run start'"
  "alias pnpmt='pnpm run test'"
  "alias pnpmr='pnpm run'"
  "alias pnpmp='pnpm preview'"
  "alias pnpmi='pnpm install'"
  "alias npmd='npm run dev'"
  "alias npmb='npm run build'"
  "alias npms='npm run start'"
  "alias npmt='npm run test'"
  "alias npmr='npm run'"
  "alias npmi='npm install'"
  "alias xUnlighthouse='pnpm dlx unlighthouse --site'"
  "alias checkNodeVersion='pnpmx is-my-node-vulnerable'"

  "# ----Navigation Aliases----"
  "alias cl='clear'"
  "alias neo='fastfetch'"
  "alias toUpdate='sudo dnf update'"
  "alias toInstall='toUpdate && sudo dnf install'"
  "alias pl='ping 8.8.8.8'"
  "alias cb='cd ..'"
  "alias cbb='cd ../..'"
  "alias lg='lazygit'"
  "alias rgr='ranger'"
  "alias rmf='rm -rf'"

  "# ----Directory Shortcuts----"
  "alias this='code .'"
  "alias hm='cd ~'"
  "alias hd='cd ~/Dev/'"
  "alias hi='cd ~/Imágenes'"
  "alias hw='cd ~/Descargas'"
  "alias hdo='cd ~/Documentos'"
  "alias projs='cd ~/Dev/projects/'"
  "alias study='cd ~/Dev/platzi/'"
  "alias OpenSrc='cd ~/Dev/cmt'"
  "alias prueba='cd ~/Dev/try'"

  "# ----Git Aliases----"
  "alias ggclone='git clone'"
  "alias ggcmt='git commit -am'"
  "alias ggadd='git add .'"
  "alias ggsta='git status'"
  "alias gglog='git log'"
  "alias ggswi='git switch'"

  "# ----System Aliases----"
  "alias reload='source $HOME/.zshrc'"
  "alias btop='bpytop'"
  "alias python='python3'"

  "# ----Ollama Aliases----"
  "alias ol='ollama'"
  "alias olr='ollama run'"
  "alias oll='ollama list'"
  "alias olp='ollama ps'"
  "alias ols='ollama stop'"
  "alias olrm='ollama rm'"

  "# ----Custom Aliases----"
  "alias matt='npx skills@latest add https://github.com/mattpocock/skills'"
  "alias autoskills='npx skills@latest'"
)
